# -*- coding: utf-8 -*-
"""EAS_XGBoost_Prediksi_Hujan_JawaTimur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaGx600l5UKrZ1h4CfGmWyBXdhinL3qL

# 🌧️ Prediksi Hujan Jawa Timur — XGBoost Classification Pipeline
**Mata Kuliah:** Pembelajaran Mesin — EAS  
**Dataset:** BMKG Climate Data (climate_data_clean.csv)  
**Target:** Klasifikasi hujan/tidak hujan (RR > 0)  
**Wilayah fokus:** Jawa Timur  

---
### Alur notebook
| Bagian | Isi |
|--------|-----|
| 1 | Import & Load Data |
| 2 | Filter Jawa Timur |
| 3 | Feature Engineering |
| 4 | EDA & Visualisasi |
| 5 | Preprocessing (encoding, scaling, split) |
| 6 | Handling Imbalanced Data (SMOTE) |
| 7 | Training XGBoost |
| 8 | Evaluasi Model |
| 9 | Feature Importance |
| 10 | Simpan Model (untuk Streamlit) |

## Bagian 1 — Import Library & Load Data
"""

# Install jika belum tersedia
!pip install xgboost imbalanced-learn shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve, ConfusionMatrixDisplay)
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
import shap
import joblib

plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.size'] = 11
print("✅ Semua library berhasil diimport")

# ── Load data ──
# Jika di Google Colab, upload file terlebih dahulu atau mount Google Drive
from google.colab import files
uploaded = files.upload()

df_raw = pd.read_csv('climate_data_clean.csv', parse_dates=['date'])

print(f"Shape data mentah : {df_raw.shape}")
print(f"Kolom             : {df_raw.columns.tolist()}")
print(f"Rentang tanggal   : {df_raw['date'].min()} s/d {df_raw['date'].max()}")
print(f"Provinsi unik     : {df_raw['province_name'].unique()}")
df_raw.head(3)

"""## Bagian 2 — Filter Wilayah Jawa Timur

Kita fokus ke Jawa Timur untuk memastikan pola iklim homogen dan model lebih presisi.

"""

# Filter Jawa Timur
df = df_raw[df_raw['province_name'] == 'Jawa Timur'].copy()
df = df.sort_values(['station_id', 'date']).reset_index(drop=True)

print(f"Shape data Jawa Timur : {df.shape}")
print(f"Jumlah stasiun        : {df['station_id'].nunique()}")
print(f"Stasiun unik:")
print(df[['station_id','station_name','region_name']].drop_duplicates().to_string(index=False))

"""## Bagian 3 — Feature Engineering

### Target variable
- `rain` = 1 jika `RR > 0` (ada hujan), 0 jika tidak

### Fitur yang dibuat
| Kelompok | Fitur |
|----------|-------|
| Temporal | `day_of_year`, `month`, `week_of_year`, `season` |
| Lag | `RR_lag1`, `RR_lag2`, `RR_lag3` (curah hujan hari sebelumnya) |
| Rolling | `RR_roll3`, `RH_roll3`, `Tavg_roll3` (rata-rata 3 hari) |
| Meteorologi | semua kolom numerik asli |
| Arah angin | `ddd_car` di-encode ke sin/cos (circular encoding) |

"""

# ── Target variable ──
df['rain'] = (df['RR'] > 0).astype(int)
print(f"Distribusi target:")
print(df['rain'].value_counts())
print(f"\nRasio hujan: {df['rain'].mean():.2%}")

# ── Fitur temporal ──
df['day_of_year'] = df['date'].dt.dayofyear
df['week_of_year'] = df['date'].dt.isocalendar().week.astype(int)

# Musim: Desember-Februari = hujan (1), Juni-Agustus = kemarau (2), lainnya = peralihan (3)
def get_season(m):
    if m in [12, 1, 2]: return 1   # musim hujan
    elif m in [6, 7, 8]: return 2  # musim kemarau
    else: return 3                  # peralihan
df['season'] = df['month'].apply(get_season)

# ── Circular encoding arah angin ddd_car ──
wind_dir_map = {'N':0,'NNE':22.5,'NE':45,'ENE':67.5,'E':90,'ESE':112.5,
                'SE':135,'SSE':157.5,'S':180,'SSW':202.5,'SW':225,'WSW':247.5,
                'W':270,'WNW':292.5,'NW':315,'NNW':337.5,'C':0}
df['ddd_car_deg'] = df['ddd_car'].map(wind_dir_map).fillna(0)
df['wind_sin'] = np.sin(np.radians(df['ddd_car_deg']))
df['wind_cos'] = np.cos(np.radians(df['ddd_car_deg']))

# ── Lag features (per stasiun, disorting tanggal) ──
for lag in [1, 2, 3]:
    df[f'RR_lag{lag}']  = df.groupby('station_id')['RR'].shift(lag)
    df[f'RH_lag{lag}']  = df.groupby('station_id')['RH_avg'].shift(lag)

# ── Rolling features (per stasiun) ──
for col in ['RR', 'RH_avg', 'Tavg', 'ff_avg']:
    df[f'{col}_roll3'] = df.groupby('station_id')[col].transform(
        lambda x: x.shift(1).rolling(3, min_periods=1).mean()
    )
    df[f'{col}_roll7'] = df.groupby('station_id')[col].transform(
        lambda x: x.shift(1).rolling(7, min_periods=1).mean()
    )

# ── Rain streak: berapa hari hujan berturut-turut sebelumnya ──
def rain_streak(s):
    streak = np.zeros(len(s), dtype=int)
    for i in range(1, len(s)):
        streak[i] = streak[i-1] + 1 if s.iloc[i-1] > 0 else 0
    return pd.Series(streak, index=s.index)

df['rain_streak'] = df.groupby('station_id')['RR'].apply(rain_streak).values

# Drop baris awal yang NaN karena lag
df = df.dropna().reset_index(drop=True)
print(f"Shape setelah feature engineering: {df.shape}")
print(f"Kolom baru: {[c for c in df.columns if c not in df_raw.columns]}")

"""## Bagian 4 — Exploratory Data Analysis (EDA)"""

fig, axes = plt.subplots(2, 2, figsize=(14, 9))
fig.suptitle('EDA — Data Cuaca Jawa Timur', fontsize=13, fontweight='bold')

# 4a. Distribusi target
ax = axes[0, 0]
counts = df['rain'].value_counts()
bars = ax.bar(['Tidak Hujan (0)', 'Hujan (1)'], counts.values,
              color=['#4A90D9', '#E8593C'], edgecolor='white', linewidth=0.5)
for bar, val in zip(bars, counts.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50,
            f'{val:,}\n({val/len(df):.1%})', ha='center', va='bottom', fontsize=10)
ax.set_title('Distribusi Target (rain)', fontweight='bold')
ax.set_ylabel('Jumlah observasi')
ax.grid(axis='y', alpha=0.3)

# 4b. Rata-rata curah hujan per bulan
ax = axes[0, 1]
monthly = df.groupby('month')['RR'].mean()
ax.bar(monthly.index, monthly.values, color='#4A90D9', edgecolor='white')
ax.set_title('Rata-rata Curah Hujan per Bulan', fontweight='bold')
ax.set_xlabel('Bulan')
ax.set_ylabel('RR rata-rata (mm)')
ax.set_xticks(range(1, 13))
ax.set_xticklabels(['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'])
ax.grid(axis='y', alpha=0.3)

# 4c. Distribusi RH_avg vs rain
ax = axes[1, 0]
for label, grp in df.groupby('rain'):
    ax.hist(grp['RH_avg'], bins=40, alpha=0.6, density=True,
            label='Hujan' if label==1 else 'Tidak Hujan',
            color='#E8593C' if label==1 else '#4A90D9')
ax.set_title('Distribusi Kelembapan (RH_avg) by Label', fontweight='bold')
ax.set_xlabel('RH_avg (%)')
ax.set_ylabel('Densitas')
ax.legend()
ax.grid(alpha=0.3)

# 4d. Probabilitas hujan per bulan
ax = axes[1, 1]
prob = df.groupby('month')['rain'].mean()
ax.plot(prob.index, prob.values, marker='o', color='#E8593C', linewidth=2, markersize=7)
ax.fill_between(prob.index, prob.values, alpha=0.15, color='#E8593C')
ax.set_title('Probabilitas Hujan per Bulan', fontweight='bold')
ax.set_xlabel('Bulan')
ax.set_ylabel('P(Hujan)')
ax.set_xticks(range(1, 13))
ax.set_xticklabels(['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'])
ax.set_ylim(0, 1)
ax.grid(alpha=0.3)
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))

plt.tight_layout()
plt.savefig('eda_cuaca_jatim.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Plot EDA tersimpan: eda_cuaca_jatim.png")

# Korelasi fitur numerik dengan target
num_cols = ['Tn','Tx','Tavg','RH_avg','ss','ff_x','ff_avg','ddd_x',
            'RR_lag1','RR_lag2','RR_lag3','RH_lag1','RH_avg_roll3','RR_roll3',
            'RR_roll7','Tavg_roll3','rain_streak','day_of_year','month',
            'wind_sin','wind_cos']
corr = df[num_cols + ['rain']].corr()['rain'].drop('rain').sort_values()

fig, ax = plt.subplots(figsize=(9, 7))
colors = ['#E8593C' if v > 0 else '#4A90D9' for v in corr.values]
ax.barh(corr.index, corr.values, color=colors, edgecolor='white', linewidth=0.4)
ax.axvline(0, color='gray', linewidth=0.8, linestyle='--')
ax.set_title('Korelasi Fitur terhadap Target (rain)', fontweight='bold')
ax.set_xlabel('Korelasi Pearson')
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('correlation_features.png', bbox_inches='tight', dpi=150)
plt.show()

"""## Bagian 5 — Preprocessing"""

# Fitur yang dipakai untuk training
FEATURES = [
    # Meteorologi dasar
    'Tn', 'Tx', 'Tavg', 'RH_avg', 'ss', 'ff_x', 'ff_avg', 'ddd_x',
    # Temporal
    'month', 'day_of_year', 'week_of_year', 'season',
    # Arah angin (circular encoded)
    'wind_sin', 'wind_cos',
    # Lag features
    'RR_lag1', 'RR_lag2', 'RR_lag3',
    'RH_lag1', 'RH_lag2', 'RH_lag3',
    # Rolling features
    'RR_roll3', 'RR_roll7',
    'RH_avg_roll3', 'RH_avg_roll7',
    'Tavg_roll3', 'Tavg_roll7',
    'ff_avg_roll3', 'ff_avg_roll7',
    # Rain streak
    'rain_streak',
]

TARGET = 'rain'

X = df[FEATURES]
y = df[TARGET]

print(f"Jumlah fitur  : {X.shape[1]}")
print(f"Jumlah sampel : {X.shape[0]}")
print(f"\nDistribusi target:")
print(y.value_counts())
print(f"\nClass imbalance ratio: {y.value_counts()[0]/y.value_counts()[1]:.2f}:1")

# Train-test split: 80/20, stratified (jaga rasio kelas)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train set : {X_train.shape[0]:,} baris")
print(f"Test set  : {X_test.shape[0]:,} baris")
print(f"\nDistribusi y_train: {dict(y_train.value_counts())}")
print(f"Distribusi y_test : {dict(y_test.value_counts())}")

"""## Bagian 6 — Handling Imbalanced Data (SMOTE)

Data cuaca sering imbalanced: hari tidak hujan jauh lebih banyak dari hari hujan.  
SMOTE (Synthetic Minority Over-sampling Technique) membuat sampel sintetis kelas minoritas.  
**Penting:** SMOTE hanya diterapkan pada training set, BUKAN test set.

"""

smote = SMOTE(random_state=42, k_neighbors=5)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

print(f"Sebelum SMOTE: {dict(y_train.value_counts())}")
print(f"Setelah SMOTE: {dict(pd.Series(y_train_sm).value_counts())}")
print(f"\nUkuran training set setelah SMOTE: {X_train_sm.shape[0]:,} baris")

"""## Bagian 7 — Training XGBoost Classifier

Hyperparameter yang dipakai:
| Parameter | Nilai | Keterangan |
|-----------|-------|------------|
| `n_estimators` | 300 | Jumlah pohon |
| `max_depth` | 6 | Kedalaman maksimal pohon |
| `learning_rate` | 0.05 | Step size per iterasi |
| `subsample` | 0.8 | Fraksi sampel per pohon |
| `colsample_bytree` | 0.8 | Fraksi fitur per pohon |
| `eval_metric` | `logloss` | Metrik untuk early stopping |

"""

model = XGBClassifier(
    n_estimators       = 300,
    max_depth          = 6,
    learning_rate      = 0.05,
    subsample          = 0.8,
    colsample_bytree   = 0.8,
    min_child_weight   = 5,
    gamma              = 0.1,
    reg_alpha          = 0.1,
    reg_lambda         = 1.0,
    use_label_encoder  = False,
    eval_metric        = 'logloss',
    early_stopping_rounds = 20,
    random_state       = 42,
    n_jobs             = -1
)

model.fit(
    X_train_sm, y_train_sm,
    eval_set=[(X_test, y_test)],
    verbose=50
)

print(f"\n✅ Training selesai!")
print(f"Best iteration: {model.best_iteration}")

# Cross-validation (5-fold stratified) pada data TRAIN asli (sebelum SMOTE)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(
    XGBClassifier(
        n_estimators=300, max_depth=6, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8, use_label_encoder=False,
        eval_metric='logloss', random_state=42, n_jobs=-1
    ),
    X_train, y_train, cv=cv, scoring='roc_auc', n_jobs=-1
)
print(f"Cross-Validation ROC-AUC (5-fold): {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

"""## Bagian 8 — Evaluasi Model"""

y_pred      = model.predict(X_test)
y_pred_prob = model.predict_proba(X_test)[:, 1]

roc_auc = roc_auc_score(y_test, y_pred_prob)
print("=" * 55)
print(f"  ROC-AUC Score : {roc_auc:.4f}")
print("=" * 55)
print("\nClassification Report:")
print(classification_report(y_test, y_pred,
      target_names=['Tidak Hujan', 'Hujan']))

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle('Evaluasi Model XGBoost — Jawa Timur', fontsize=13, fontweight='bold')

# Confusion matrix
ax = axes[0]
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=['Tidak Hujan', 'Hujan'])
disp.plot(ax=ax, colorbar=False, cmap='Blues')
ax.set_title('Confusion Matrix', fontweight='bold')
for text in ax.texts:
    text.set_fontsize(13)

# ROC Curve
ax = axes[1]
fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
ax.plot(fpr, tpr, color='#E8593C', lw=2, label=f'XGBoost (AUC = {roc_auc:.4f})')
ax.plot([0,1],[0,1], color='gray', linestyle='--', lw=1, label='Random classifier')
ax.fill_between(fpr, tpr, alpha=0.08, color='#E8593C')
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.set_title('ROC Curve', fontweight='bold')
ax.legend(loc='lower right')
ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('evaluasi_model.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Plot evaluasi tersimpan: evaluasi_model.png")

"""## Bagian 9 — Feature Importance (XGBoost + SHAP)

Dua cara melihat pentingnya fitur:
1. **XGBoost built-in** — berdasarkan gain (seberapa banyak fitur ini mengurangi loss)
2. **SHAP values** — menjelaskan kontribusi tiap fitur ke tiap prediksi individu

"""

# XGBoost feature importance (top 20)
importance = pd.Series(model.feature_importances_, index=FEATURES)
importance = importance.sort_values(ascending=True).tail(20)

fig, ax = plt.subplots(figsize=(9, 7))
colors = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(importance)))
importance.plot(kind='barh', ax=ax, color=colors, edgecolor='white', linewidth=0.3)
ax.set_title('Top 20 Feature Importance (XGBoost Gain)', fontweight='bold')
ax.set_xlabel('Importance Score')
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('feature_importance_xgb.png', bbox_inches='tight', dpi=150)
plt.show()

# SHAP values (sample 2000 baris agar cepat)
sample_idx = np.random.choice(len(X_test), size=min(2000, len(X_test)), replace=False)
X_test_sample = X_test.iloc[sample_idx]

explainer    = shap.TreeExplainer(model)
shap_values  = explainer.shap_values(X_test_sample)

plt.figure(figsize=(10, 7))
shap.summary_plot(shap_values, X_test_sample, plot_type='bar',
                  max_display=15, show=False)
plt.title('SHAP Feature Importance (Top 15)', fontweight='bold')
plt.tight_layout()
plt.savefig('shap_importance.png', bbox_inches='tight', dpi=150)
plt.show()

# SHAP beeswarm plot — lihat arah pengaruh tiap fitur
plt.figure(figsize=(10, 7))
shap.summary_plot(shap_values, X_test_sample, max_display=15, show=False)
plt.title('SHAP Summary (Beeswarm) — Arah Pengaruh Fitur', fontweight='bold')
plt.tight_layout()
plt.savefig('shap_beeswarm.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Plot SHAP tersimpan")

"""## Bagian 10 — Simpan Model & Artefak (untuk Streamlit)

File yang disimpan:
| File | Kegunaan di Streamlit |
|------|----------------------|
| `model_xgboost_jatim.pkl` | Model utama untuk prediksi |
| `features_list.pkl` | Daftar fitur yang dipakai |
| `model_info.pkl` | Metadata (threshold, ROC-AUC, dll) |

"""

# Simpan model
joblib.dump(model, 'model_xgboost_jatim.pkl')

# Simpan daftar fitur (WAJIB sama persis saat load di Streamlit)
joblib.dump(FEATURES, 'features_list.pkl')

# Simpan metadata
model_info = {
    'roc_auc'         : roc_auc,
    'best_iteration'  : model.best_iteration,
    'features'        : FEATURES,
    'threshold'       : 0.5,
    'province'        : 'Jawa Timur',
    'target_col'      : 'rain',
    'rain_definition' : 'RR > 0 mm',
    'n_train'         : len(X_train_sm),
    'n_test'          : len(X_test),
    'cv_roc_auc_mean' : float(cv_scores.mean()),
    'cv_roc_auc_std'  : float(cv_scores.std()),
}
joblib.dump(model_info, 'model_info.pkl')

print("✅ File tersimpan:")
print("   • model_xgboost_jatim.pkl")
print("   • features_list.pkl")
print("   • model_info.pkl")
print()
print(f"📊 Ringkasan performa:")
print(f"   ROC-AUC (test)  : {roc_auc:.4f}")
print(f"   CV ROC-AUC      : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
print(f"   Features dipakai: {len(FEATURES)}")
print(f"   Training samples: {len(X_train_sm):,} (setelah SMOTE)")
print(f"   Test samples    : {len(X_test):,}")

"""---
## ✅ Pipeline Selesai!

### Output yang dihasilkan
| Output | Deskripsi |
|--------|-----------|
| `model_xgboost_jatim.pkl` | Model XGBoost terlatih |
| `features_list.pkl` | Daftar 30+ fitur |
| `model_info.pkl` | Metadata & metrik |
| `eda_cuaca_jatim.png` | Plot EDA |
| `correlation_features.png` | Korelasi fitur |
| `evaluasi_model.png` | Confusion matrix + ROC |
| `feature_importance_xgb.png` | XGBoost importance |
| `shap_importance.png` | SHAP bar chart |
| `shap_beeswarm.png` | SHAP beeswarm |

### Langkah selanjutnya → Streamlit Dashboard
Muat model dengan:
```python
import joblib
model    = joblib.load('model_xgboost_jatim.pkl')
features = joblib.load('features_list.pkl')
info     = joblib.load('model_info.pkl')
```

"""